services:
  balance-service:
    container_name: balance-service
    build:
      target: production
      context: .
      args:
        APP: balance-service
    env_file:
      - .env
    # override
    environment:
      - RATE_SERVICE_URL=http://rate-service:3001
    ports:
      - 3000:3000
    image: balance-service:latest
  rate-service:
    container_name: rate-service
    build:
      target: production
      context: .
      args:
        APP: rate-service
    env_file:
      - .env
    image: rate-service:latest
    ports:
      - 3001:3001